# language: yaml
name: Release

on:
  push:
    tags:
      - 'v*'   # triggers on v1.2.3 etc.

permissions:
  contents: write  # required to create/upload release assets

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build source tarball
        run: |
          set -eu
          ver="${GITHUB_REF_NAME#v}"
          repo="${GITHUB_REPOSITORY##*/}"
          git archive --format=tar --prefix="${repo}-${ver}/" "v${ver}" | gzip -n > "${repo}-${ver}.tar.gz"
          sha256sum "${repo}-${ver}.tar.gz" > "${repo}-${ver}.tar.gz.sha256"

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.tar.gz
            *.sha256
            *.asc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
